name: plant_diagnosis_app
description: ØªØ·Ø¨ÙŠÙ‚ ØªØ´Ø®ÙŠØµ Ø§Ù„Ù†Ø¨Ø§ØªØ§Øª
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.2
  flutter_localizations:
    sdk: flutter
  http: ^1.1.0
  image_picker: ^1.0.7
  file_picker: ^10.2.0
  sqflite: ^2.3.0
  sqflite_common_ffi_web: ^0.4.2
  sqflite_common_ffi: ^2.0.0
  google_sign_in: ^6.1.0
  geolocator: ^10.1.0
  intl: ^0.20.0
  device_info_plus: ^10.1.0

  
  path: ^1.8.0
dev_dependencies:
  flutter_test:
    sdk: flutter
 # flutter_lints: ^2.0.0
  path_provider: ^2.0.15
 # dio: ^6.1.2
  flutter_cache_manager: ^3.3.0
  cached_network_image: ^3.2.3


flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/diseases_all.json
    - assets/placeholder.png
    - assets/logo.png
    - assets/images/soil.jpg
    - assets/images/protection.jpg
    - assets/images/pests.jpg
    - assets/images/diseases.jpg
    - assets/images/seasons.jpg
    - assets/images/books.jpg
    - assets/images/support.jpg
    - assets/images/tomato_icon.png
    - assets/images/potato_icon.png
    - assets/images/wheat_icon.png
    - assets/images/corn_icon.png
    - assets/images/pepper_icon.png
    - assets/images/cucumber_icon.png
    - assets/images/rice_icon.png
    - assets/images/strawberry_icon.png
    - assets/images/grape_icon.png
    - assets/images/apple_icon.png
    - assets/images/apple_fire_blight.png
    - assets/images/grape_downy.png
    - assets/images/strawberry_grey_mold.png
    - assets/images/rice_blast.png

    # ðŸ¦  Ø£Ù…Ø±Ø§Ø¶ Ø§Ù„Ø·Ù…Ø§Ø·Ù…
    - assets/images/tomato_wilt.png
    - assets/images/tomato_soft_rot.png
    - assets/images/tomato_powder.png
    - assets/images/aphids.png
    - assets/images/whitefly.png
    - assets/images/tomato_early_blight.png
    - assets/images/blossom_rot.png
    - assets/images/gray_mold.png
    - assets/images/maize_rust.png

    # ðŸ¥” Ø£Ù…Ø±Ø§Ø¶ Ø§Ù„Ø¨Ø·Ø§Ø·Ø³
    - assets/images/potato_blight.png
    - assets/images/potato_dry_rot.png
    - assets/images/beetle.png

    # ðŸŒ¾ Ø£Ù…Ø±Ø§Ø¶ Ø§Ù„Ù‚Ù…Ø­
    - assets/images/yellow_rust.png
    - assets/images/wheat_powder.png
    - assets/images/smut.png

    # ðŸŒ½ Ø£Ù…Ø±Ø§Ø¶ Ø§Ù„Ø°Ø±Ø©
    - assets/images/armyworm.png
    - assets/images/fusarium.png

    # ðŸŒ¶ï¸ Ø£Ù…Ø±Ø§Ø¶ Ø§Ù„ÙÙ„ÙÙ„
    - assets/images/pepper_wilt.png
    - assets/images/red_spider.png
    - assets/images/pepper_leaf_spot.png

    # ðŸ¥’ Ø£Ù…Ø±Ø§Ø¶ Ø§Ù„Ø®ÙŠØ§Ø±
    - assets/images/cucumber_downy.png
    - assets/images/bacterial_wilt.png
    - assets/plantix_final.db
    - assets/plant_relational.json
    - assets/crops_ar.json
    - assets/disease_images/
    - assets/plantix_icons/



