name: Flutter Build APK

# متى يعمل هذا الـ workflow
on:
  push:
    branches:
      - main      # عند كل دفع للكود على الفرع الرئيسي
  workflow_dispatch:  # إمكانية التشغيل يدويًا من GitHub

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. استرجاع الكود من المستودع
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. تثبيت Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
         channel: 'stable'
         flutter-version: '3.35.5'

      # 3. تثبيت التبعيات
      - name: Install dependencies
        run: flutter pub get

      # 4. بناء APK بنمط release
      - name: Build APK
        run: flutter build apk --release

      # 5. رفع الـ APK كـ artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
